name: Deploy Firebase Functions

on:
  push:
    branches:
      - master  # Branch where github action gets triggered

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Match this version to the version in functions/package.json

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install dependencies
      run: npm install
      working-directory: ./functions

    - name: Run tests
      run: npm test
      working-directory: ./functions

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: firebase deploy --only functions